<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="suyi-PC" name="Test" tests="5" failures="2" timestamp="18 Oct 2016 07:07:11 GMT" time="295.275" errors="0">
  <testcase name="Regist" time="33.579" classname="com.my.test.TestCase"/>
  <testcase name="Bank" time="108.882" classname="com.my.test.TestCase"/>
  <testcase name="Recharge" time="55.086" classname="com.my.test.TestCase">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.my.business.SimpleBusiness.Recharge(Unknown Source)
	at com.my.test.TestCase.Recharge(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- Recharge -->
  <testcase name="Withdrawals" time="33.494" classname="com.my.test.TestCase"/>
  <testcase name="Ticket" time="57.932" classname="com.my.test.TestCase">
    <failure type="java.lang.AssertionError" message="expected [恭喜您，支付成功] but found [恭喜您,支付成功]">
      <![CDATA[java.lang.AssertionError: expected [恭喜您，支付成功] but found [恭喜您,支付成功]
	at com.my.business.SimpleBusiness.BuyTicket(Unknown Source)
	at com.my.test.TestCase.Ticket(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Ticket -->
</testsuite> <!-- Test -->
